#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f lfsr4.vcd

#run Verilator to transform Verilog into C++, including C++ testbench
#(this operation is what is called creating a wrapper)
verilator -Wall --cc --trace lfsr4.sv --exe lfsr4_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlfsr4.mk Vlfsr4

#run executable simulation file
obj_dir/Vlfsr4