#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f lfsr7.vcd

#run Verilator to transform Verilog into C++, including C++ testbench
#(this operation is what is called creating a wrapper)
verilator -Wall --cc --trace lfsr7.sv --exe lfsr7_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlfsr7.mk Vlfsr7

#run executable simulation file
obj_dir/Vlfsr7